dist: xenial
language: node_js

install:
  - npm ci

script:
  - npm run build
  - npm run test
  - echo "sleep random number of seconds 1-10 to prevent blockchain collisions" && sleep "$(( ( RANDOM % 10 )  + 1 ))"
  - npm run verify

before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
  - scripts/ci/version.sh

deploy:
  - provider: script
    script: bash scripts/ci/publish.sh
    skip_cleanup: true