dist: xenial
language: node_js

install:
  - npm ci

script:
  - npm run build
  - npm run test
  - echo "sleep random number of seconds 1-10 to prevent blockchain collisions" && sleep "$(( ( RANDOM % 10 )  + 1 ))"
  - npm run verify

before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

deploy:
  - provider: script
    on:
      branch: development
      tags: false
    script: bash scripts/ci/publish-development.sh
    skip_cleanup: true
  - provider: script
    on:
      branch: staging
      tags: false
    script: bash scripts/ci/publish-staging.sh
    skip_cleanup: true
  - provider: script
    on:
      branch: production
      tags: false
    script: bash scripts/ci/publish-production.sh
    skip_cleanup: true
